### ISSUE TITLE
missing releases executable

### ISSUE THREAD

**Issue by eric15342335** [Teinc3/solitaire#2]
https://github.com/Teinc3/solitaire/blob/6fd30770a4a2ecfd336bd987dc1cf232540bbd2e/README.md?plain=1#L16-L18

Is there a plan to publish releases?

**Comment by Teinc3** [comment]
Yes, I plan to upload executables artifacts once the `Persistence` module is completed.

However there are currently some major issues that I might need to prioritize fixing, including builtin ANSI text coloring and keybinding functionalities. Unfortunately I cannot ensure cross-platform support for now but I will try to solve them asap

**Comment by Teinc3** [comment]
Binaries for Windows and OSX are now added as part of the latest release `v1.0.0`.
However I am too lazy to dockerize my project or to use my ubuntu web worker to compile a Unix-compatible binary, so those will probably be unavailable for quite some time.

**Comment by eric15342335** [comment]
Great to hear that! However, I encountered some `missing dll` errors when trying to launch `win32-solitaire.exe` on windows 11.
![image](https://github.com/Teinc3/solitaire/assets/70310617/c377a426-abee-458d-8a5c-3fac1ac9e05d)
![image](https://github.com/Teinc3/solitaire/assets/70310617/5250bcad-1f9f-44d9-a97c-b41930884d9b)
As a end user, I probably won't have those libraries installed on my system.
I think the solution is either:
* shift the respective dlls in a zip file, or
* statically link to those libraries with the flag `-static`

Please comment out if I were wrong.

Edit:
From my experience, adding `-static` flag to makefile will break some linux/osx configurations. Since they don't have the appropriate `*.a` libraries installed (required by static linking). While some mingw distributions typically shipped with it already.
